### ISSUE TITLE
Create a PUT endpoint for workflow submission

### ISSUE THREAD

**Issue by mkiwala** [genome/ptero-workflow#205]
Currently we support a POST endpoint.

This involves adding a uuid unique column on the workflow table and changing the urls of workflows to include the uuid instead of integer workflow id value.

On POST, the workflow service would produce the uuid.  On PUT, the client is expected to generate their own uuid.

**Comment by davidlmorton** [comment]
The utility of this is small compared to the work involved.  Wont fix.
