### ISSUE TITLE
Support hard canceling a workflow

### ISSUE THREAD

**Issue by mark-burnett** [genome/ptero-workflow#43]

**Comment by davidlmorton** [comment]
Warm shutdown of a workflow is already supported, this ticket is to implement hard canceling (i.e. killing running jobs).

**Comment by davidlmorton** [comment]
Support warm .vs. cold shutdown with header fields or query-string arguments?

**Comment by mkiwala** [comment]
I would have thought to just support cold shutdown for all executor services that supports hard cancelling (hopefully both shell-command and lsf), and support warm shutdown everywhere else.  When would someone opt for only a warm shutdown?

**Comment by davidlmorton** [comment]
I think there exist situations where you just want to stop the workflow from progressing and not stop the jobs.  For example, say you're 2/3rds of the way through some cpu intensive job and it will be able to checkpoint in the future, but you don't want downstream steps to run.
