### ISSUE TITLE
rabbitmq-plugins conflict when running multiple rabbits

### ISSUE THREAD

**Issue by iferguson90** [genome/ptero-workflow#63]
This is technically not a workflow issue but it breaks tests in workflow.

A fresh install of rabbitmq with homebrew seems to enable several rabbitmq plugins that try to bind to a default port. When multiple rabbits spin-up, the plugins all try to bind to the same port, and the rabbitmq instance fails to boot.

I had to do the following before tests would run:
```
$ rabbitmq-plugins disable rabbitmq_stomp
$ rabbitmq-plugins disable rabbitmq_mqtt
$ rabbitmq-plugins disable rabbitmq_management
```

This seems to change some global rabbit configuration. A quick look over the rabbit documentation provides no obvious insight on how to disable plugins through configuration, environment variables, or command-line switches (as opposed to using `rabbitmq-plugins`).

**Comment by davidlmorton** [comment]
I don't think this is an issue for us in testing anymore.
