### ISSUE TITLE
Automate test of 'OutputsAlreadySet' error

### ISSUE THREAD

**Issue by davidlmorton** [genome/ptero-workflow#81]
We've hand-tested the code that disallows setting the outputs of an Execution more than once, but it required hacking the ptero_workflow_execution_wrapper.  Figure out a way to automate that test that doesn't dig into the implementation too heavily.

**Comment by mkiwala** [comment]
I believe this issue is now irrelevant now that we've eliminated ptero_workflow_execution_wrapper.
